import { BasicColumn } from '/@/components/Table';

//列表数据
export const columns: BasicColumn[] = [
  {
    title: '供应商名',
    align: 'center',
    sorter: true,
    dataIndex: 'orgName',
    width: 150,
    resizable: true,
  },
  {
    title: '手机',
    align: 'center',
    dataIndex: 'cellPhone',
    width: 120,
    resizable: true,
  },
  {
    title: '电话',
    align: 'center',
    dataIndex: 'phone',
    width: 100,
    resizable: true,
  },
  // {
  //   title: '折扣率',
  //   align: 'center',
  //   dataIndex: 'discount',
  //   width: 100,
  //   resizable: true,
  // },
  {
    title: '联系人',
    align: 'center',
    dataIndex: 'contact',
    width: 100,
    resizable: true,
  },
  {
    title: '地址',
    align: 'center',
    dataIndex: 'address',
    width: 150,
    resizable: true,
  },
  {
    title: '传真',
    align: 'center',
    dataIndex: 'faxes',
    width: 100,
    resizable: true,
  },
  {
    title: 'QQ',
    align: 'center',
    dataIndex: 'qq',
    width: 100,
    resizable: true,
  },
  {
    title: '微信',
    align: 'center',
    dataIndex: 'wechat',
    width: 100,
    resizable: true,
  },
  {
    title: '邮箱',
    align: 'center',
    dataIndex: 'email',
    width: 150,
    resizable: true,
  },
  // {
  //   title: '业务员',
  //   align: 'center',
  //   dataIndex: 'salesmanName',
  //   width: 100,
  //   resizable: true,
  // },
  {
    title: '备注',
    align: 'center',
    dataIndex: 'remark',
    width: 120,
    resizable: true,
  },
];
