import { BasicColumn } from '/@/components/Table';

//列表数据
export const columns: BasicColumn[] = [
  {
    title: '单号',
    align: 'center',
    dataIndex: 'billNo',
    width: 150,
    resizable: true,
  },
  {
    title: '日期',
    align: 'center',
    dataIndex: 'billDate',
    width: 150,
    resizable: true,
  },
  {
    title: '欠款类型',
    align: 'center',
    dataIndex: 'type_dictText',
    width: 100,
    resizable: true,
    slots: { customRender: 'type_dictText' },
  },
  {
    title: '本单金额',
    align: 'center',
    dataIndex: 'amount',
    width: 100,
    resizable: true,
  },
  {
    title: '付款金额',
    align: 'center',
    dataIndex: 'paymentAmount',
    width: 100,
    resizable: true,
  },
  {
    title: '优惠金额',
    align: 'center',
    dataIndex: 'discountAmount',
    width: 100,
    resizable: true,
  },
  {
    title: '欠款金额',
    align: 'center',
    dataIndex: 'debtAmount',
    width: 100,
    resizable: true,
  },
  {
    title: '送货车号',
    align: 'center',
    dataIndex: 'careNo',
    width: 100,
    resizable: true,
  },
  {
    title: '合同号',
    align: 'center',
    dataIndex: 'contractCode',
    width: 100,
    resizable: true,
  },
  {
    title: '业务员',
    align: 'center',
    dataIndex: 'userName',
    width: 100,
    resizable: true,
  },
  {
    title: '制单人',
    align: 'center',
    dataIndex: 'createName',
    width: 100,
    resizable: true,
  },
  {
    title: '备注',
    align: 'center',
    dataIndex: 'remark',
    width: 120,
    resizable: true,
  },
];
