export default {
  panels: [
    {
      index: 0,
      name: 1,
      height: 93,
      width: 210,
      paperHeader: 55.5,
      paperFooter: 235.5,
      printElements: [
        {
          options: {
            left: 178.5,
            top: 9,
            height: 21,
            width: 249,
            title: '夏门东兴岳贸易有限公司送货单',
            right: 427.5,
            bottom: 28.5,
            vCenter: 303,
            hCenter: 15,
            coordinateSync: false,
            widthHeightSync: false,
            fontFamily: 'SimSun',
            fontSize: 17.25,
            fontWeight: 'bold',
            textContentVerticalAlign: 'middle',
            qrCodeLevel: 0,
          },
          printElementType: {
            title: '这是更新后的元素',
            type: 'text',
          },
        },
        {
          options: {
            left: 456,
            top: 30,
            height: 9.75,
            width: 121.5,
            title: '单据编号',
            field: 'billNo',
            testData: '202410040008',
            coordinateSync: false,
            widthHeightSync: false,
            fontFamily: 'SimSun',
            fontSize: 10.5,
            qrCodeLevel: 0,
            qid: 'phone_1',
            right: 586.5,
            bottom: 34.5,
            vCenter: 525.75,
            hCenter: 29.625,
            color: '#ff0000',
          },
          printElementType: {
            title: '这是更新后的元素',
            type: 'text',
          },
        },
        {
          options: {
            left: 295.5,
            top: 43.5,
            height: 9.75,
            width: 132,
            title: '电话',
            field: 'phone',
            testData: '18888888888',
            coordinateSync: false,
            widthHeightSync: false,
            fontFamily: 'SimSun',
            fontSize: 10.5,
            qrCodeLevel: 0,
            qid: 'address_2',
            right: 426,
            bottom: 52.5,
            vCenter: 360,
            hCenter: 47.625,
          },
          printElementType: {
            title: '这是更新后的元素',
            type: 'text',
          },
        },
        {
          options: {
            left: 16.5,
            top: 43.5,
            height: 9.75,
            width: 183,
            title: '客户名称',
            field: 'customerCom',
            testData: '张三三',
            coordinateSync: false,
            widthHeightSync: false,
            fontFamily: 'SimSun',
            fontSize: 10.5,
            qrCodeLevel: 0,
            right: 201.75,
            bottom: 53.25,
            vCenter: 110.25,
            hCenter: 48.375,
          },
          printElementType: {
            title: '这是更新后的元素',
            type: 'text',
          },
        },
        {
          options: {
            left: 456,
            top: 43.5,
            height: 9.75,
            width: 115.5,
            title: '开单日期',
            field: 'createDate',
            testData: '2024/10/06',
            coordinateSync: false,
            widthHeightSync: false,
            fontFamily: 'SimSun',
            fontSize: 10.5,
            qrCodeLevel: 0,
            qid: 'billNo_1',
            right: 578.25,
            bottom: 53.25,
            vCenter: 520.5,
            hCenter: 48.375,
          },
          printElementType: {
            title: '这是更新后的元素',
            type: 'text',
          },
        },
        {
          options: {
            left: 15,
            top: 57,
            height: 54,
            width: 565.5,
            fields: [
              {
                text: '序号',
                field: 'seq',
              },
              {
                text: '订单编号',
                field: 'orderNo',
              },
              {
                text: '物料编号',
                field: 'code',
              },
              {
                text: '产品货号',
                field: 'code1',
              },
              {
                text: '货号',
                field: 'code2',
              },
              {
                text: '產品編號',
                field: 'code3',
              },
              {
                text: '商品全名',
                field: 'name',
              },
              {
                text: '物料名称',
                field: 'name1',
              },
              {
                text: '物料名称',
                field: 'name2',
              },
              {
                text: '通用名称',
                field: 'name3',
              },
              {
                text: '货品名称',
                field: 'name4',
              },
              {
                text: '货物名称',
                field: 'name5',
              },
              {
                text: '產品名稱',
                field: 'name6',
              },
              {
                text: '品名',
                field: 'name7',
              },
              {
                text: '名称',
                field: 'name8',
              },
              {
                text: '商品名称',
                field: 'name9',
              },
              {
                text: '名称简写',
                field: 'shortName',
              },
              {
                text: '规格型号',
                field: 'spec',
              },
              {
                text: '規格型號',
                field: 'spec1',
              },
              {
                text: '型号',
                field: 'spec2',
              },
              {
                text: '规格',
                field: 'spec3',
              },
              {
                text: '剂型',
                field: 'spec_2',
              },
              {
                text: '包装',
                field: 'pack',
              },
              {
                text: '品名及规格',
                field: 'nameSpec',
              },
              {
                text: '生产厂商',
                field: 'firm',
              },
              {
                text: '生产企业',
                field: 'firm1',
              },
              {
                text: '厂商',
                field: 'firm2',
              },
              {
                text: '产商地址',
                field: 'firmAddress',
              },
              {
                text: '生产地址',
                field: 'firmAddress1',
              },
              {
                text: '生产日期',
                field: 'productDate',
              },
              {
                text: '单位',
                field: 'unit',
              },
              {
                text: '單位',
                field: 'unit1',
              },
              {
                text: '颜色',
                field: 'color',
              },
              {
                text: '数量',
                field: 'count',
              },
              {
                text: '重量',
                field: 'weight',
              },
              {
                text: '单价',
                field: 'price',
              },
              {
                text: '单价(元)',
                field: 'price',
              },
              {
                text: '金额',
                field: 'amount',
              },
              {
                text: '批号',
                field: 'batchNum',
              },
              {
                text: '生产批号',
                field: 'batchNum2',
              },
              {
                text: '有效期',
                field: 'validity',
              },
              {
                text: '零售价',
                field: 'retailPrice',
              },
              {
                text: '批准文号',
                field: 'approvalNo',
              },
              {
                text: '注册证号',
                field: 'certificateNo',
              },
              {
                text: '备注',
                field: 'remark',
              },
            ],
            field: 'table',
            footerFormatter:
              'function (options, rows, data, currentPageGridRowsData) {\n    // options 配置信息\n    // rows 总行数据信息\n    // data 整个数据信息\n    // currentPageGridRowsData 当前页的数据信息\n    // 算当前页金额小计\n    if (data && data[\'total\']) {\n      let price = cal(currentPageGridRowsData);\n      let capital = Nzh.cn.toMoney(data[\'total\'], { complete: false, outSymbol: false });\n      return (\n        \'<tr><td colspan="5" style="text-align: left"></td>\' +\n        \' <td colspan="3" style="text-align: left;">页小计：￥\' + price + \'</td>\' +\n        \'</tr>\'\n      );\n    }\n\n    return \'<tr><td colspan="5" style="text-align: left"></td><td colspan="3" style="text-align: left;">页小计：￥0</td></tr>\';\n  }',
            qid: 'table',
            right: 580.5,
            bottom: 111,
            vCenter: 297.75,
            hCenter: 84,
            coordinateSync: false,
            widthHeightSync: false,
            textAlign: 'center',
            fontFamily: 'SimSun',
            columns: [
              [
                {
                  width: 39.58543817843519,
                  title: '序号',
                  field: 'seq',
                  checked: true,
                  columnId: 'seq',
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: 'center',
                },
                {
                  width: 125.31926199006985,
                  title: '商品名称',
                  field: 'name9',
                  checked: true,
                  columnId: 'name9',
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: 'left',
                },
                {
                  width: 76.12288712378198,
                  title: '规格型号',
                  field: 'spec',
                  checked: true,
                  columnId: 'spec',
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                },
                {
                  width: 48.03478751488069,
                  title: '单位',
                  field: 'unit',
                  checked: true,
                  columnId: 'unit',
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                },
                {
                  width: 50.032925072629666,
                  title: '数量',
                  field: 'count',
                  checked: true,
                  columnId: 'count',
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                },
                {
                  width: 59.022637855362376,
                  title: '单价',
                  field: 'price',
                  checked: true,
                  columnId: 'price',
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                },
                {
                  width: 60.09056982743971,
                  title: '金额',
                  field: 'amount',
                  checked: true,
                  columnId: 'amount',
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                },
                {
                  width: 107.29149243740054,
                  title: '备注',
                  field: 'remark',
                  checked: true,
                  columnId: 'remark',
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                },
              ],
            ],
          },
          printElementType: {
            title: '总合计',
            type: 'table',
            editable: true,
            columnDisplayEditable: true,
            columnDisplayIndexEditable: true,
            columnTitleEditable: true,
            columnResizable: true,
            columnAlignEditable: true,
            isEnableEditField: true,
            isEnableContextMenu: true,
            isEnableInsertRow: true,
            isEnableDeleteRow: true,
            isEnableInsertColumn: true,
            isEnableDeleteColumn: true,
            isEnableMergeCell: true,
          },
        },
        {
          options: {
            left: 16.5,
            top: 115.5,
            height: 9.75,
            width: 183,
            title: '地址',
            field: 'address',
            testData: '收货地址收货地收货地址',
            coordinateSync: false,
            widthHeightSync: false,
            fontFamily: 'SimSun',
            fontSize: 9,
            qrCodeLevel: 0,
            qid: 'signCom_1',
            right: 202.5,
            bottom: 143.25,
            vCenter: 111,
            hCenter: 138.375,
            fontWeight: 'bold',
          },
          printElementType: {
            title: '这是更新后的元素',
            type: 'text',
          },
        },
        {
          options: {
            left: 16.5,
            top: 130.5,
            height: 9.75,
            width: 183,
            title: '电话',
            field: 'phone_1',
            testData: '18888888888',
            coordinateSync: false,
            widthHeightSync: false,
            fontFamily: 'SimSun',
            fontSize: 9,
            qrCodeLevel: 0,
            qid: 'address_1',
            right: 198.75,
            bottom: 223.5,
            vCenter: 107.25,
            hCenter: 218.625,
            fontWeight: 'bold',
          },
          printElementType: {
            title: '这是更新后的元素',
            type: 'text',
          },
        },
        {
          options: {
            left: 378,
            top: 130.5,
            height: 9.75,
            width: 183,
            title: '客户签字：',
            coordinateSync: false,
            widthHeightSync: false,
            fontFamily: 'SimSun',
            fontSize: 9,
            qrCodeLevel: 0,
            qid: 'phone_2',
            right: 560.25,
            bottom: 125.25,
            vCenter: 468.75,
            hCenter: 120.375,
            fontWeight: 'bold',
          },
          printElementType: {
            title: '这是更新后的元素',
            type: 'text',
          },
        },
        {
          options: {
            left: 280.5,
            top: 240,
            height: 9.75,
            width: 76.5,
            title: '第二联红客户',
            coordinateSync: false,
            widthHeightSync: false,
            fontFamily: 'Microsoft YaHei',
            fontSize: 9,
            qrCodeLevel: 0,
            qid: 'address_2',
            right: 356.25,
            bottom: 251.25,
            vCenter: 318,
            hCenter: 246.375,
          },
          printElementType: {
            title: '这是更新后的元素',
            type: 'text',
          },
        },
        {
          options: {
            left: 381,
            top: 240,
            height: 9.75,
            width: 76.5,
            title: '第三联黄回单',
            coordinateSync: false,
            widthHeightSync: false,
            fontFamily: 'Microsoft YaHei',
            fontSize: 9,
            qrCodeLevel: 0,
            qid: 'address_2',
            right: 425.49998474121094,
            bottom: 248.50003051757812,
            vCenter: 387.24998474121094,
            hCenter: 243.62503051757812,
          },
          printElementType: {
            title: '这是更新后的元素',
            type: 'text',
          },
        },
        {
          options: {
            left: 178.5,
            top: 240,
            height: 9.75,
            width: 76.5,
            title: '第一联白存根',
            coordinateSync: false,
            widthHeightSync: false,
            fontFamily: 'Microsoft YaHei',
            fontSize: 9,
            qrCodeLevel: 0,
            qid: 'address_2',
            right: 433.5,
            bottom: 251.25,
            vCenter: 299.25,
            hCenter: 246.375,
          },
          printElementType: {
            title: '这是更新后的元素',
            type: 'text',
          },
        },
      ],
      paperNumberLeft: 534,
      paperNumberTop: 238.5,
      paperNumberContinue: true,
      paperNumberFormat: '页码: ${paperNo}/${paperCount}',
      watermarkOptions: {
        content: '',
        rotate: 25,
        timestamp: false,
        format: 'YYYY-MM-DD HH:mm',
        fillStyle: 'rgba(184, 184, 184, 0.3)',
        fontSize: '14px',
        width: 200,
        height: 200,
      },
      panelLayoutOptions: {
        layoutType: 'column',
        layoutRowGap: 0,
        layoutColumnGap: 0,
      },
    },
  ],
};
