export default {
  panels: [
    {
      index: 0,
      name: 1,
      height: 93,
      width: 210,
      paperHeader: 96,
      paperFooter: 226.5,
      printElements: [
        {
          options: {
            left: 223.5,
            top: 13.5,
            height: 18,
            width: 154.5,
            title: '单位',
            field: 'company',
            testData: '贵阳市XXX科技有限公司',
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            qid: 'address_2',
            right: 377.2500228881836,
            bottom: 31.5,
            vCenter: 300.0000228881836,
            hCenter: 22.5,
            fontFamily: 'SimSun',
            fontSize: 14.25,
            hideTitle: true,
            fontWeight: 'bold',
            textContentVerticalAlign: 'middle',
          },
          printElementType: {
            title: '文本',
            type: 'text',
          },
        },
        {
          options: {
            left: 199.5,
            top: 42,
            height: 9.75,
            width: 256.5,
            title: '地址',
            field: 'address',
            testData: '贵州省贵阳市 城城城城城',
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            qid: 'phone_2',
            right: 532.5,
            bottom: 18.75,
            vCenter: 368.25,
            hCenter: 13.875,
            fontFamily: 'SimSun',
            fontSize: 9,
          },
          printElementType: {
            title: '文本',
            type: 'text',
          },
        },
        {
          options: {
            left: 460.5,
            top: 42,
            height: 9.75,
            width: 130.5,
            title: 'NO',
            right: 580.5,
            bottom: 18.75,
            vCenter: 520.5,
            hCenter: 13.875,
            field: 'billNo',
            testData: '202410030001',
            coordinateSync: false,
            widthHeightSync: false,
            fontFamily: 'SimSun',
            fontSize: 11.25,
            qrCodeLevel: 0,
            fontWeight: 'bold',
          },
          printElementType: {
            title: '这是更新后的元素',
            type: 'text',
          },
        },
        {
          options: {
            left: 199.5,
            top: 55.5,
            height: 9.75,
            width: 256.5,
            title: '电话',
            field: 'tel',
            testData: '18888999999/28888888888',
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            qid: 'address_2',
            right: 457.75000762939453,
            bottom: 67.75000762939453,
            vCenter: 329.50000762939453,
            hCenter: 62.87500762939453,
            fontFamily: 'SimSun',
            fontSize: 9,
          },
          printElementType: {
            title: '文本',
            type: 'text',
          },
        },
        {
          options: {
            left: 285,
            top: 70.5,
            height: 9.75,
            width: 156,
            title: '客户电话',
            field: 'contactTel_1',
            testData: '13552521537',
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            qid: 'contact_1',
            right: 421.7500305175781,
            bottom: 57.25000762939453,
            vCenter: 365.5000305175781,
            hCenter: 52.37500762939453,
            fontFamily: 'SimSun',
            fontSize: 9,
          },
          printElementType: {
            title: '文本',
            type: 'text',
          },
        },
        {
          options: {
            left: 451.5,
            top: 70.5,
            height: 9.75,
            width: 112.5,
            title: '制单人员',
            field: 'createBy',
            testData: '李某某',
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            qid: 'phone_2',
            right: 561.2500305175781,
            bottom: 53.50000762939453,
            vCenter: 505.0000305175781,
            hCenter: 48.62500762939453,
            fontFamily: 'SimSun',
            fontSize: 9,
          },
          printElementType: {
            title: '文本',
            type: 'text',
          },
        },
        {
          options: {
            left: 19.5,
            top: 70.5,
            height: 9.75,
            width: 258,
            title: '客户名称',
            field: 'company_1',
            testData: '周小晓',
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            qid: 'address_1',
            right: 273,
            bottom: 53.25,
            vCenter: 159,
            hCenter: 48.375,
            fontFamily: 'SimSun',
            fontSize: 9,
          },
          printElementType: {
            title: '文本',
            type: 'text',
          },
        },
        {
          options: {
            left: 285,
            top: 84,
            height: 9.75,
            width: 154.5,
            title: '联系人',
            field: 'contact_1',
            testData: '张三李四',
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            qid: 'customer_1',
            right: 397.5,
            bottom: 70.5,
            vCenter: 341.25,
            hCenter: 65.625,
            fontFamily: 'SimSun',
            fontSize: 9,
          },
          printElementType: {
            title: '文本',
            type: 'text',
          },
        },
        {
          options: {
            left: 451.5,
            top: 84,
            height: 9.75,
            width: 112.5,
            title: '送货日期',
            field: 'deliveryDate',
            testData: '2024/10/03',
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            qid: 'phone_3',
            right: 565.7500305175781,
            bottom: 70.75000762939453,
            vCenter: 509.5000305175781,
            hCenter: 65.87500762939453,
            fontFamily: 'SimSun',
            fontSize: 9,
          },
          printElementType: {
            title: '文本',
            type: 'text',
          },
        },
        {
          options: {
            left: 19.5,
            top: 84,
            height: 9.75,
            width: 259.5,
            title: '客户地址',
            field: 'address_1',
            testData: '贵州省贵阳市劝解观山湖区城中里城',
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            fontFamily: 'SimSun',
            fontSize: 9,
          },
          printElementType: {
            title: '文本',
            type: 'text',
          },
        },
        {
          options: {
            left: 13.5,
            top: 96,
            height: 54,
            width: 550,
            fields: [
              {
                text: '序号',
                field: 'seq',
              },
              {
                text: '订单编号',
                field: 'orderNo',
              },
              {
                text: '物料编号',
                field: 'code',
              },
              {
                text: '产品货号',
                field: 'code1',
              },
              {
                text: '货号',
                field: 'code1',
              },
              {
                text: '產品編號',
                field: 'code3',
              },
              {
                text: '商品全名',
                field: 'name',
              },
              {
                text: '物料名称',
                field: 'name1',
              },
              {
                text: '物料名称',
                field: 'name2',
              },
              {
                text: '通用名称',
                field: 'name3',
              },
              {
                text: '货品名称',
                field: 'name4',
              },
              {
                text: '產品名稱',
                field: 'name5',
              },
              {
                text: '品名',
                field: 'name6',
              },
              {
                text: '名称简写',
                field: 'shortName',
              },
              {
                text: '规格型号',
                field: 'spec',
              },
              {
                text: '規格型號',
                field: 'spec1',
              },
              {
                text: '型号',
                field: 'spec2',
              },
              {
                text: '剂型',
                field: 'spec_2',
              },
              {
                text: '包装',
                field: 'pack',
              },
              {
                text: '品名及规格',
                field: 'nameSpec',
              },
              {
                text: '生产厂商',
                field: 'firm',
              },
              {
                text: '生产企业',
                field: 'firm1',
              },
              {
                text: '厂商',
                field: 'firm2',
              },
              {
                text: '产商地址',
                field: 'firmAddress',
              },
              {
                text: '生产地址',
                field: 'firmAddress1',
              },
              {
                text: '生产日期',
                field: 'productDate',
              },
              {
                text: '单位',
                field: 'unit',
              },
              {
                text: '單位',
                field: 'unit1',
              },
              {
                text: '颜色',
                field: 'color',
              },
              {
                text: '数量',
                field: 'count',
              },
              {
                text: '重量',
                field: 'weight',
              },
              {
                text: '单价',
                field: 'price',
              },
              {
                text: '单价(元)',
                field: 'price',
              },
              {
                text: '金额',
                field: 'amount',
              },
              {
                text: '批号',
                field: 'batchNum',
              },
              {
                text: '有效期',
                field: 'validity',
              },
              {
                text: '零售价',
                field: 'retailPrice',
              },
              {
                text: '批准文号',
                field: 'approvalNo',
              },
              {
                text: '注册证号',
                field: 'certificateNo',
              },
              {
                text: '备注',
                field: 'remark',
              },
            ],
            field: 'table',
            footerFormatter:
              'function (options, rows, data, currentPageGridRowsData) {\n    // options 配置信息\n    // rows 总行数据信息\n    // data 整个数据信息\n    // currentPageGridRowsData 当前页的数据信息\n    if (data && currentPageGridRowsData && 0 < currentPageGridRowsData.length) {\n      let price = cal(currentPageGridRowsData);\n      let capital = Nzh.cn.toMoney(price, { complete: false, outSymbol: false });\n      return \'<tr><td colspan="5" style="border: 1px solid">合计金额（大写）：\' + capital + \'整</td><td colspan="3">小写：￥\' + price + \'</td></tr>\';\n    }\n\n    return \'<tr><td colspan="5" style="border: 1px solid">合计金额（大写）：</td><td colspan="3">小写：￥</td></tr>\';\n  }',
            qid: 'table',
            right: 562.75,
            bottom: 129.75,
            vCenter: 287.75,
            hCenter: 102.75,
            coordinateSync: false,
            widthHeightSync: false,
            fontFamily: 'SimSun',
            fontSize: 7.5,
            autoCompletion: true,
            columns: [
              [
                {
                  width: 30.786143023255818,
                  title: '序号',
                  field: 'seq',
                  checked: true,
                  columnId: 'seq',
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: 'center',
                },
                {
                  width: 161.18141511627903,
                  title: '商品名称',
                  field: 'name',
                  checked: true,
                  columnId: 'name',
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: 'center',
                },
                {
                  width: 89.42779069767444,
                  title: '规格',
                  field: 'spec',
                  checked: true,
                  columnId: 'spec',
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: 'center',
                },
                {
                  width: 38.372093023255815,
                  title: '单位',
                  field: 'unit',
                  checked: true,
                  columnId: 'unit',
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: 'center',
                },
                {
                  width: 38.372093023255815,
                  title: '数量',
                  field: 'count',
                  checked: true,
                  columnId: 'count',
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: 'center',
                },
                {
                  width: 63.95348837209302,
                  title: '单价',
                  field: 'price',
                  checked: true,
                  columnId: 'price',
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: 'center',
                },
                {
                  width: 63.95348837209302,
                  title: '金额',
                  field: 'amount',
                  checked: true,
                  columnId: 'amount',
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: 'center',
                },
                {
                  width: 63.95348837209302,
                  title: '备注',
                  field: 'remark',
                  checked: true,
                  columnId: 'remark',
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                },
              ],
            ],
          },
          printElementType: {
            title: '页合计',
            type: 'table',
            editable: true,
            columnDisplayEditable: true,
            columnDisplayIndexEditable: true,
            columnTitleEditable: true,
            columnResizable: true,
            columnAlignEditable: true,
            isEnableEditField: true,
            isEnableContextMenu: true,
            isEnableInsertRow: true,
            isEnableDeleteRow: true,
            isEnableInsertColumn: true,
            isEnableDeleteColumn: true,
            isEnableMergeCell: true,
          },
        },
        {
          options: {
            left: 507.75,
            top: 135,
            height: 9.75,
            width: 123,
            transform: 90,
            title: '①白存根②红客户③黄回单',
            right: 630.75,
            bottom: 144.75,
            vCenter: 569.25,
            hCenter: 139.875,
            coordinateSync: false,
            widthHeightSync: false,
            fixed: true,
            qrCodeLevel: 0,
            fontFamily: 'SimSun',
            fontSize: 9.75,
          },
          printElementType: {
            title: '这是更新后的元素',
            type: 'text',
          },
        },
        {
          options: {
            left: 309,
            top: 228,
            height: 9.75,
            width: 259.5,
            title: '收货单位及经手人（签章）',
            right: 428.25,
            bottom: 236.25,
            vCenter: 368.25,
            hCenter: 231.375,
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            fontFamily: 'SimSun',
            fontSize: 10.5,
          },
          printElementType: {
            title: '这是更新后的元素',
            type: 'text',
          },
        },
        {
          options: {
            left: 19.5,
            top: 228,
            height: 9.75,
            width: 280.5,
            title: '送货单位及经手人（签章）',
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            right: 306.0000305175781,
            bottom: 224.2500076293945,
            vCenter: '165.75003051757812',
            hCenter: 219.3750076293945,
            fontFamily: 'SimSun',
            fontSize: 10.5,
          },
          printElementType: {
            title: '这是更新后的元素',
            type: 'text',
          },
        },
      ],
      paperNumberLeft: 573,
      paperNumberTop: 207,
      paperNumberDisabled: true,
      paperNumberContinue: true,
      watermarkOptions: {
        content: '',
        rotate: 25,
        timestamp: false,
        format: 'YYYY-MM-DD HH:mm',
        fillStyle: 'rgba(184, 184, 184, 0.3)',
        fontSize: '14px',
        width: 200,
        height: 200,
      },
      panelLayoutOptions: {
        layoutType: 'column',
        layoutRowGap: 0,
        layoutColumnGap: 0,
      },
    },
  ],
};
